/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: 6x9.bdf
 *      Font: -Misc-Fixed-Medium-R-Normal--9-90-75-75-C-60-ISO10646-1
 *      Size: 9   Baseline at: 6
 * For chars: 0123456789 -/Monday Tuesday Wednesday Thursday Friday Saturday Sunday
 */

#include "font-6x9.h"

static const uint8_t PROGMEM _font_data_6x9[] = {
  /* codepoint ' ' plain bytes */

  /* codepoint '-' RLE/nibble */
  0x05,0x08,

  /* codepoint '/' plain bytes */
  0x30,0x08,0x04,0x03,

  /* codepoint '0' plain bytes */
  0x1e,0x21,0x21,0x1e,

  /* codepoint '1' plain bytes */
  0x22,0x3f,0x20,

  /* codepoint '2' plain bytes */
  0x22,0x31,0x29,0x26,

  /* codepoint '3' plain bytes */
  0x21,0x25,0x27,0x19,

  /* codepoint '4' plain bytes */
  0x18,0x14,0x12,0x3f,0x10,

  /* codepoint '5' plain bytes */
  0x27,0x25,0x25,0x19,

  /* codepoint '6' plain bytes */
  0x1e,0x25,0x25,0x18,

  /* codepoint '7' plain bytes */
  0x01,0x31,0x09,0x07,

  /* codepoint '8' plain bytes */
  0x1a,0x25,0x25,0x1a,

  /* codepoint '9' plain bytes */
  0x06,0x29,0x29,0x1e,

  /* codepoint 'F' plain bytes */
  0x3f,0x05,0x05,0x01,

  /* codepoint 'M' plain bytes */
  0x3f,0x02,0x0c,0x02,0x3f,

  /* codepoint 'S' plain bytes */
  0x12,0x25,0x29,0x12,

  /* codepoint 'T' RLE/4 */
  0x26,0x01,0x3f,0x01,

  /* codepoint 'W' plain bytes */
  0x3f,0x10,0x0c,0x10,0x3f,

  /* codepoint 'a' plain bytes */
  0x18,0x24,0x24,0x3c,

  /* codepoint 'd' plain bytes */
  0x18,0x24,0x24,0x3f,

  /* codepoint 'e' plain bytes */
  0x18,0x34,0x2c,0x28,

  /* codepoint 'h' plain bytes */
  0x3f,0x04,0x04,0x38,

  /* codepoint 'i' plain bytes */
  0x24,0x3d,0x20,

  /* codepoint 'n' plain bytes */
  0x3c,0x04,0x04,0x38,

  /* codepoint 'o' plain bytes */
  0x18,0x24,0x24,0x18,

  /* codepoint 'r' plain bytes */
  0x3c,0x08,0x04,0x08,

  /* codepoint 's' plain bytes */
  0x28,0x2c,0x34,0x14,

  /* codepoint 't' plain bytes */
  0x04,0x1f,0x24,0x10,

  /* codepoint 'u' plain bytes */
  0x1c,0x20,0x20,0x3c,

  /* codepoint 'y' plain bytes */
  0x5c,0xa0,0xa0,0x7c,
};

static const struct GlyphData PROGMEM _font_glyphs_6x9[] = {
  {.codepoint = ' ',    .width= 6, .stripe_begin=0, .stripe_end=0, .left_margin=0, .right_margin=0, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '-',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset=   0},
  {.codepoint = '/',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=   2},
  {.codepoint = '0',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=   6},
  {.codepoint = '1',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset=  10},
  {.codepoint = '2',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  13},
  {.codepoint = '3',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  17},
  {.codepoint = '4',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  21},
  {.codepoint = '5',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  26},
  {.codepoint = '6',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  30},
  {.codepoint = '7',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  34},
  {.codepoint = '8',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  38},
  {.codepoint = '9',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  42},
  {.codepoint = 'F',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  46},
  {.codepoint = 'M',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  50},
  {.codepoint = 'S',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  55},
  {.codepoint = 'T',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset=  59},
  {.codepoint = 'W',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  63},
  {.codepoint = 'a',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  68},
  {.codepoint = 'd',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  72},
  {.codepoint = 'e',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  76},
  {.codepoint = 'h',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  80},
  {.codepoint = 'i',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset=  84},
  {.codepoint = 'n',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  87},
  {.codepoint = 'o',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  91},
  {.codepoint = 'r',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  95},
  {.codepoint = 's',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  99},
  {.codepoint = 't',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 103},
  {.codepoint = 'u',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 107},
  {.codepoint = 'y',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 111},
};

const struct FontData PROGMEM font_6x9 = {
  .available_glyphs = 30,
  .baseline = 6,
  .stripes = 1,
  .bits = _font_data_6x9,
  .glyphs = _font_glyphs_6x9
};
