/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: message.bdf
 *      Font: -Misc-Fixed-Bold-R-Normal--13-120-75-75-C-80-ISO10646-1
 *      Size: 13   Baseline at: 10
 * For chars: Henner Zeller
 */

#include "font-message.h"

static const uint8_t PROGMEM _font_data_message[] = {
  /* codepoint ' ' plain bytes */

  /* codepoint 'H' RLE/4 */
  0x2e,0xff,0x10,0xff,
  0x2e,0x03,0x00,0x03,

  /* codepoint 'Z' RLE/4 */
  0x55,0x81,0xc1,0x61,0x31,  0x15,0x19,0x0f,0x07,
  0x2e,0x03,0x02,0x02,

  /* codepoint 'e' plain bytes */
  0xf0,0xf8,0x48,0x48,0x48,0x78,0x70,
  0x01,0x03,0x02,0x02,0x02,0x03,0x01,

  /* codepoint 'l' plain bytes */
  0x01,0xff,0xff,0x00,
  0x02,0x03,0x03,0x02,

  /* codepoint 'n' RLE/4 */
  0x66,0xf8,0x10,0x08,0xf8,  0x01,0xf0,
  0x2e,0x03,0x00,0x03,

  /* codepoint 'r' RLE/nibble */
  0x12,0xf8,0x10,  0x12,0x08,0x18,  0x01,0x10,
  0x52,0x03,0x00,
};

static const struct GlyphData PROGMEM _font_glyphs_message[] = {
  {.codepoint = ' ',    .width= 8, .stripe_begin=1, .stripe_end=0, .left_margin=0, .right_margin=0, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = 'H',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset=   0},
  {.codepoint = 'Z',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset=   8},
  {.codepoint = 'e',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  21},
  {.codepoint = 'l',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_PLAIN(0), .data_offset=  35},
  {.codepoint = 'n',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset=  43},
  {.codepoint = 'r',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset=  54},
};

const struct FontData PROGMEM font_message = {
  .available_glyphs = 7,
  .baseline = 10,
  .stripes = 2,
  .bits = _font_data_message,
  .glyphs = _font_glyphs_message
};
