/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: timetext.bdf
 *      Font: -FreeType-TeXGyreAdventor-Medium-R-Normal--24-240-72-72-P-118-ISO10646-1
 *      Size: 35   Baseline at: 18
 * For chars: 0123456789:
 */
#ifndef FONT_timetext_
#define FONT_timetext_

#include "bdfont-support.h"

/* font containing 11 characters */
extern const struct FontData PROGMEM font_timetext;

#endif /* FONT_timetext_ */
