/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: message.bdf
 *      Font: -Misc-Fixed-Bold-R-Normal--13-120-75-75-C-80-ISO10646-1
 *      Size: 13   Baseline at: 10
 * For chars: Henner Zeller
 */
#ifndef FONT_message_
#define FONT_message_

#include "bdfont-support.h"

/* font containing 7 characters */
extern const struct FontData PROGMEM font_message;

#endif /* FONT_message_ */
